### ISSUE TITLE
[Bug]: size() doesnt work

### ISSUE THREAD

**Issue by putrafajarh** [ibrahimBougaoua/filament-rating-star#20]
### What happened?

RatingStarColumn::make('stars')->size('sm')

```
Method IbrahimBougaoua\FilamentRatingStar\Columns\RatingStarColumn::size does not exist.
```

### How to reproduce the bug

RatingStarColumn::make('stars')->size('sm')

### Package Version

^1.0

### PHP Version

8.2

### Laravel Version

10.x

### Which operating systems does with happen with?

Linux

**Comment by putrafajarh** [comment]
version `^1.0` doesnt work.
I need to manually update package to dev-main to get latest, maybe you can check it on packagist?

"ibrahimbougaoua/filament-rating-star": "dev-main"

**Comment by pablozagni** [comment]
Undefined variable $getSize

if I specify size, error is shown.

![image](https://github.com/ibrahimBougaoua/filament-rating-star/assets/10306819/9c5b7918-1ea4-4bcd-a7d5-4728b5ac3125)
