### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nforst** [ibrahimBougaoua/filament-rating-star#3]
### What happened?

It appears that there is an issue with the rating display when adding a single star. Specifically, the rating is being duplicated, making it difficult to interact with the lower instance.

![image](https://github.com/ibrahimBougaoua/filament-rating-star/assets/30083590/6a38ac22-ea65-4deb-9d1d-12935e886316)

### How to reproduce the bug

Update the config to the following

```
return [
    'stars' => [
        'star1' => '1',
        'star2' => '2',
        'star3' => '3',
        'star4' => '4',
        'star5' => '5',
        'star6' => '6',
        'star7' => '7',
    ]
];
```

### Package Version

0.0.1

### PHP Version

8.2

### Laravel Version

10.10

### Which operating systems does with happen with?

macOS

**Comment by ibrahimBougaoua** [comment]
Yes,should be more dynamic,i will fix it soon,thanks.
