### ISSUE TITLE
What about an Infolist component?

### ISSUE THREAD

**Issue by billmn** [ibrahimBougaoua/filament-rating-star#5]
### What happened?

Have you considered creating an Infolist component as well?

### How to reproduce the bug

---

### Package Version

0.0.1

### PHP Version

8.2

### Laravel Version

10.22.0

### Notes

I tried to create a FR but I think the discussions in this repository are disabled because I get a 404 error: https://github.com/ibrahimBougaoua/filament-rating-star/discussions/new?category=ideas

**Comment by ibrahimBougaoua** [comment]
Hi,added to todo list,thanks.
